name: Generate KDocs Wiki

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Sets up JDK for JVM
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # Updates wrapper permissions
      - name: Change wrapper permissions
        run: chmod +x ./gradlew


      # Generates KDocs through Dokka
      - name: Generate KDocs
        run: ./gradlew dokkaGfm

      # Collects and Posts Generated Docs To GitHub Wiki
      - name: Push Wiki Changes
        uses: Andrew-Chen-Wang/github-wiki-action@v3
        env:
          # Make sure you have that / at the end. We use rsync
          # WIKI_DIR's default is wiki/
          WIKI_DIR: build/dokka/gfm/
          GH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          GH_MAIL: ${{ secrets.EMAIL }}
          GH_NAME: ${{ github.repository_owner }}
          EXCLUDED_FILES: "**/index.md"