name: Generate KDocs Wiki

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Generates KDocs through Dokka
      - name: Generate KDocs
        run: ./gradlew Dokkahtml

      # Collects and Posts Generated Docs To GitHub Wiki
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "build/dokka/html"