name: Generate KDocs Wiki

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Sets up JDK for JVM
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # Updates wrapper permissions
      - name: Change wrapper permissions
        run: chmod +x ./gradlew


      # Generates KDocs through Dokka
      - name: Generate KDocs
        run: ./gradlew dokkaGfm

      # Collects and Posts Generated Docs To GitHub Wiki
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "**/*gfm/*.md"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}